name: Run C++/C tests for Libft

on:
  push:
    branches:
      - main
      - test-flow
jobs:
  run-tests:
    name : Run container for build and tests
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build test container
        run : docker build . -t=libft_test:latest