name: Run C++/C tests for Libft

on:
  push:
    branches:
      - main
      - test-flow
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell : bash
    steps:
      - name : Get deps
        run : sudo apt-get install clang-format g++ gcc cmake wget tree
      - name : Build source
        run : mkdir build && cmake -S . -B build && cmake --build build
      - name : Run CTest
        run : cd build/tests && ctest
    
