name: Run C++/C tests for Libft

on:
  push:
    branches:
      - main
      - test-flow
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Bump CMake
        run : sudo apt-get install cmake
      - uses: actions/checkout@v3
      - name: Run unit tests
        uses: HorstBaerbel/action-ctest@1.1
        with:
          sourcedir: '.'
          builddir: 'build'